
name: Deploy
on:
  pull_request:
    branches:
    - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    env:
      SSH_KEY: ${{secrets.FWGHA_RSA}}
      MACHINE: fwgha@${{secrets.LIVE_SERVER_IP}}

    steps:
    - uses: actions/checkout@v2
    # - name: Use Node.js 14
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: 14
    # - name: npm install build frontend
    #   working-directory: ./Frontend
    #   run: |
    #     touch .env
    #     echo REACT_APP_GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" >> .env
    #     echo REACT_APP_BASE_URL="${{ secrets.API_URL_LIVE }}" >> .env
    #     cat .env
    #     npm ci
    #     npm run build
    # - name: npm install backend
    #   working-directory: ./Backend
    #   run: |
    #     touch .env
    #     echo products=${{ secrets.STRIPE_KEY }} >> .env
    #     echo YOUR_DOMAIN=${{ secrets.API_URL_LIVE }} >> .env
    #     echo FRONT_END_BASE_URL=${{ secrets.SITE_URL_LIVE }} >> .env
    #     echo allowedOrigins=${{ secrets.SITE_URL_LIVE }} >> .env
    #     cat .env
    #     npm ci
    - name: ssh init
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/id_rsa.pub
        echo $SSH_KEY >> ~/.ssh/id_rsa.pub
        cat ~/.ssh/id_rsa.pub
    - name: ssh test file creation
      run: |
        touch ~/test.txt
        echo "Test" >> ~/test.txt
        cat ~/test.txt
        cat ~/test.txt
        
- name: Deploy with rsync
    uses: burnett01/rsync-deployments@5.2.1
    with:
      switches: -avzr --delete
      path: ~/test.text
      remote_path: ~/
      remote_host: 185.53.57.126
      remote_user: fwgha
      remote_key: ${{ secrets.FWGPHA_KEY }}
